require "jbpros.options"
require "jbpros.keymaps"
require "jbpros.plugins"
require "jbpros.colorscheme"
require "jbpros.cmp"
require "jbpros.lsp"
require "jbpros.telescope"
require "jbpros.treesitter"
